import postgres from "postgres";

const sql = postgres(process.env.DATABASE_URL!);

const demoOpportunities = [
  {
    noticeId: "demo-001-gsa-lease-ny",
    title: "Office Space Lease - Manhattan Financial District",
    solicitationNumber: "GSA-NYC-2025-001",
    city: "New York",
    state: "NY",
    stateCode: "NY",
    cityCode: "36061",
    zip: "10004",
    description: "GSA seeks approximately 15,000 SF of office space in Lower Manhattan for Federal agency operations. Prime location near public transit.",
    responseDeadline: new Date("2026-02-15"),
  },
  {
    noticeId: "demo-002-gsa-lease-ca",
    title: "Federal Building Lease - San Francisco Bay Area",
    solicitationNumber: "GSA-SF-2025-002",
    city: "San Francisco",
    state: "CA",
    stateCode: "CA",
    cityCode: "06075",
    zip: "94102",
    description: "Lease for 25,000 SF government office building in downtown San Francisco. Must meet federal security standards.",
    responseDeadline: new Date("2026-01-30"),
  },
  {
    noticeId: "demo-003-gsa-lease-tx",
    title: "GSA Office Space - Dallas Metro",
    solicitationNumber: "GSA-DAL-2025-003",
    city: "Dallas",
    state: "TX",
    stateCode: "TX",
    cityCode: "48113",
    zip: "75201",
    description: "20,000 SF office space required for federal operations in Dallas. Parking for 50 vehicles required.",
    responseDeadline: new Date("2026-03-01"),
  },
  {
    noticeId: "demo-004-gsa-lease-fl",
    title: "Federal Office Lease - Miami",
    solicitationNumber: "GSA-MIA-2025-004",
    city: "Miami",
    state: "FL",
    stateCode: "FL",
    cityCode: "12086",
    zip: "33130",
    description: "GSA seeking 12,000 SF of modern office space in Miami for agency consolidation. Hurricane-rated building required.",
    responseDeadline: new Date("2026-02-20"),
  },
  {
    noticeId: "demo-005-gsa-lease-il",
    title: "Chicago Loop Office Space",
    solicitationNumber: "GSA-CHI-2025-005",
    city: "Chicago",
    state: "IL",
    stateCode: "IL",
    cityCode: "17031",
    zip: "60604",
    description: "30,000 SF premium office space in Chicago Loop for federal agency headquarters. Must include conference facilities.",
    responseDeadline: new Date("2026-01-25"),
  },
  {
    noticeId: "demo-006-gsa-lease-wa",
    title: "Seattle Federal Office Building",
    solicitationNumber: "GSA-SEA-2025-006",
    city: "Seattle",
    state: "WA",
    stateCode: "WA",
    cityCode: "53033",
    zip: "98101",
    description: "18,000 SF LEED-certified office space in downtown Seattle. Green building standards required.",
    responseDeadline: new Date("2026-02-28"),
  },
  {
    noticeId: "demo-007-gsa-lease-dc",
    title: "Washington DC Federal Office Space",
    solicitationNumber: "GSA-DC-2025-007",
    city: "Washington",
    state: "DC",
    stateCode: "DC",
    cityCode: "11001",
    zip: "20001",
    description: "35,000 SF high-security office space near Capitol Hill for federal operations. Enhanced security clearance required.",
    responseDeadline: new Date("2026-03-15"),
  },
  {
    noticeId: "demo-008-gsa-lease-ma",
    title: "Boston Federal Building Lease",
    solicitationNumber: "GSA-BOS-2025-008",
    city: "Boston",
    state: "MA",
    stateCode: "MA",
    cityCode: "25025",
    zip: "02108",
    description: "22,000 SF office space in Boston Financial District. Historic building renovation acceptable with compliance.",
    responseDeadline: new Date("2026-02-10"),
  },
  {
    noticeId: "demo-009-gsa-lease-ga",
    title: "Atlanta Metro Federal Office",
    solicitationNumber: "GSA-ATL-2025-009",
    city: "Atlanta",
    state: "GA",
    stateCode: "GA",
    cityCode: "13121",
    zip: "30303",
    description: "28,000 SF modern office facility in Atlanta for regional federal operations. Must accommodate 150+ employees.",
    responseDeadline: new Date("2026-01-20"),
  },
  {
    noticeId: "demo-010-gsa-lease-co",
    title: "Denver Federal Office Complex",
    solicitationNumber: "GSA-DEN-2025-010",
    city: "Denver",
    state: "CO",
    stateCode: "CO",
    cityCode: "08031",
    zip: "80202",
    description: "16,000 SF office space in downtown Denver with mountain views. Energy efficiency standards required.",
    responseDeadline: new Date("2026-02-05"),
  },
  {
    noticeId: "demo-011-gsa-lease-az",
    title: "Phoenix Federal Building Lease",
    solicitationNumber: "GSA-PHX-2025-011",
    city: "Phoenix",
    state: "AZ",
    stateCode: "AZ",
    cityCode: "04013",
    zip: "85004",
    description: "24,000 SF office space in Phoenix metro area. Climate-controlled environment and backup power required.",
    responseDeadline: new Date("2026-03-10"),
  },
  {
    noticeId: "demo-012-gsa-lease-pa",
    title: "Philadelphia Federal Office Space",
    solicitationNumber: "GSA-PHL-2025-012",
    city: "Philadelphia",
    state: "PA",
    stateCode: "PA",
    cityCode: "42101",
    zip: "19107",
    description: "19,000 SF office facility in Center City Philadelphia. Accessibility compliance mandatory.",
    responseDeadline: new Date("2026-01-28"),
  },
  {
    noticeId: "demo-013-gsa-lease-nc",
    title: "Charlotte Federal Office Lease",
    solicitationNumber: "GSA-CLT-2025-013",
    city: "Charlotte",
    state: "NC",
    stateCode: "NC",
    cityCode: "37119",
    zip: "28202",
    description: "21,000 SF professional office space in Charlotte's Uptown district for federal agency.",
    responseDeadline: new Date("2026-02-12"),
  },
  {
    noticeId: "demo-014-gsa-lease-mn",
    title: "Minneapolis Federal Building",
    solicitationNumber: "GSA-MSP-2025-014",
    city: "Minneapolis",
    state: "MN",
    stateCode: "MN",
    cityCode: "27053",
    zip: "55401",
    description: "17,000 SF heated office space in downtown Minneapolis. Winter climate control systems essential.",
    responseDeadline: new Date("2026-02-25"),
  },
  {
    noticeId: "demo-015-gsa-lease-or",
    title: "Portland Federal Office Complex",
    solicitationNumber: "GSA-PDX-2025-015",
    city: "Portland",
    state: "OR",
    stateCode: "OR",
    cityCode: "41051",
    zip: "97204",
    description: "14,000 SF sustainable office building in Portland. LEED Gold certification preferred.",
    responseDeadline: new Date("2026-03-05"),
  },
  {
    noticeId: "demo-016-gsa-lease-nv",
    title: "Las Vegas Federal Office Lease",
    solicitationNumber: "GSA-LAS-2025-016",
    city: "Las Vegas",
    state: "NV",
    stateCode: "NV",
    cityCode: "32003",
    zip: "89101",
    description: "26,000 SF office space in Las Vegas for multiple federal agencies. High-efficiency cooling required.",
    responseDeadline: new Date("2026-01-18"),
  },
  {
    noticeId: "demo-017-gsa-lease-va",
    title: "Arlington Federal Office Building",
    solicitationNumber: "GSA-ARL-2025-017",
    city: "Arlington",
    state: "VA",
    stateCode: "VA",
    cityCode: "51013",
    zip: "22201",
    description: "32,000 SF secure office facility near Pentagon. Top-secret clearance workspace included.",
    responseDeadline: new Date("2026-02-22"),
  },
  {
    noticeId: "demo-018-gsa-lease-mo",
    title: "Kansas City Federal Office Space",
    solicitationNumber: "GSA-KC-2025-018",
    city: "Kansas City",
    state: "MO",
    stateCode: "MO",
    cityCode: "29095",
    zip: "64105",
    description: "15,000 SF office space in downtown Kansas City for regional federal operations.",
    responseDeadline: new Date("2026-02-08"),
  },
  {
    noticeId: "demo-019-gsa-lease-tn",
    title: "Nashville Federal Building Lease",
    solicitationNumber: "GSA-NSH-2025-019",
    city: "Nashville",
    state: "TN",
    stateCode: "TN",
    cityCode: "47037",
    zip: "37203",
    description: "20,000 SF modern office facility in Nashville metro for federal agency consolidation.",
    responseDeadline: new Date("2026-03-12"),
  },
  {
    noticeId: "demo-020-gsa-lease-mi",
    title: "Detroit Federal Office Complex",
    solicitationNumber: "GSA-DET-2025-020",
    city: "Detroit",
    state: "MI",
    stateCode: "MI",
    cityCode: "26163",
    zip: "48226",
    description: "23,000 SF office building in downtown Detroit for federal government operations. Revitalization area preference.",
    responseDeadline: new Date("2026-01-22"),
  },
];

async function seedDemoOpportunities() {
  console.log("Starting to seed demo GSA lease opportunities...");

  let successCount = 0;
  let errorCount = 0;

  for (const opp of demoOpportunities) {
    try {
      const postedDate = new Date();
      postedDate.setDate(postedDate.getDate() - Math.floor(Math.random() * 30)); // Posted within last 30 days

      await sql`
        INSERT INTO opportunities (
          notice_id,
          title,
          solicitation_number,
          department,
          sub_tier,
          office,
          posted_date,
          type,
          base_type,
          archive_type,
          archive_date,
          type_of_set_aside,
          type_of_set_aside_description,
          response_deadline,
          naics_code,
          classification_code,
          active,
          description,
          organization_type,
          office_zipcode,
          office_city,
          office_country_code,
          office_state,
          pop_street_address,
          pop_city_code,
          pop_city_name,
          pop_state_code,
          pop_state_name,
          pop_zip,
          pop_country_code,
          pop_country_name,
          additional_info_link,
          ui_link,
          full_data,
          source,
          last_synced_at
        ) VALUES (
          ${opp.noticeId},
          ${opp.title},
          ${opp.solicitationNumber},
          ${"General Services Administration"},
          ${"Public Buildings Service"},
          ${"GSA PBS Real Property Leasing"},
          ${postedDate.toISOString()},
          ${"Solicitation"},
          ${"Solicitation"},
          ${"autocustom"},
          ${new Date(opp.responseDeadline.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString()},
          ${"NONE"},
          ${"No Set aside used"},
          ${opp.responseDeadline.toISOString()},
          ${"531120"},
          ${"X1AA"},
          ${"Yes"},
          ${opp.description},
          ${"OFFICE"},
          ${opp.zip},
          ${opp.city},
          ${"USA"},
          ${opp.stateCode},
          ${null},
          ${opp.cityCode},
          ${opp.city},
          ${opp.stateCode},
          ${opp.state},
          ${opp.zip},
          ${"USA"},
          ${"UNITED STATES"},
          ${null},
          ${`https://sam.gov/workspace/contract/opp/${opp.noticeId}/view`},
          ${JSON.stringify({
            noticeId: opp.noticeId,
            title: opp.title,
            description: opp.description,
          })},
          ${"gsa_leasing"},
          ${new Date().toISOString()}
        )
        ON CONFLICT (notice_id) DO UPDATE SET
          title = EXCLUDED.title,
          response_deadline = EXCLUDED.response_deadline,
          description = EXCLUDED.description,
          last_synced_at = EXCLUDED.last_synced_at
      `;

      console.log(`✓ Inserted: ${opp.title} (${opp.city}, ${opp.stateCode})`);
      successCount++;
    } catch (error) {
      console.error(`✗ Error inserting ${opp.noticeId}:`, error);
      errorCount++;
    }
  }

  await sql.end();

  console.log("\n=== Seed Complete ===");
  console.log(`✓ Successfully inserted: ${successCount} opportunities`);
  console.log(`✗ Errors: ${errorCount}`);
  console.log(`Total: ${successCount + errorCount} / ${demoOpportunities.length}`);
}

seedDemoOpportunities().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
