-- Insert 20 fake GSA leasing opportunities for testing
-- These are realistic-looking opportunities with various states, set-asides, and deadlines

INSERT INTO public.opportunities (
  notice_id,
  title,
  solicitation_number,
  department,
  sub_tier,
  office,
  posted_date,
  type,
  base_type,
  active,
  type_of_set_aside,
  type_of_set_aside_description,
  response_deadline,
  naics_code,
  classification_code,
  description,
  organization_type,
  office_zipcode,
  office_city,
  office_country_code,
  office_state,
  pop_street_address,
  pop_city_code,
  pop_city_name,
  pop_state_code,
  pop_state_name,
  pop_zip,
  pop_country_code,
  pop_country_name,
  ui_link,
  source
) VALUES
-- 1. Seattle Office Space - Small Business Set-Aside
(
  'fake-gsa-2025-001',
  'Office Space Lease - Seattle Federal Building',
  'GS-10P-25-RLP-0001',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 10',
  NOW() - INTERVAL '5 days',
  'Combined Synopsis/Solicitation',
  'Presolicitation',
  'Yes',
  'SBA',
  'Total Small Business Set-Aside',
  NOW() + INTERVAL '15 days',
  '531120',
  'Y1DA',
  'GSA seeks approximately 25,000 rentable square feet of office space in downtown Seattle for federal agency use. Space must be within Seattle city limits, meet security requirements, and provide adequate parking.',
  'OFFICE',
  '98101',
  'Seattle',
  'USA',
  'WA',
  'Downtown Seattle',
  'SEATTLE',
  'Seattle',
  'WA',
  'Washington',
  '98101',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-001',
  'gsa_leasing'
),

-- 2. Boston Warehouse - HUBZone
(
  'fake-gsa-2025-002',
  'Warehouse Facility Lease - Boston Metro Area',
  'GS-01P-25-RLP-0002',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 1',
  NOW() - INTERVAL '3 days',
  'Solicitation',
  'Solicitation',
  'Yes',
  'HZC',
  'HUBZone Set-Aside',
  NOW() + INTERVAL '8 days',
  '531120',
  'Y1DA',
  'Required: 40,000 SF warehouse space with loading docks in Boston metro area. Must have 24/7 access, climate control, and security systems.',
  'OFFICE',
  '02109',
  'Boston',
  'USA',
  'MA',
  'Boston Metro Area',
  'BOSTON',
  'Boston',
  'MA',
  'Massachusetts',
  '02109',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-002',
  'gsa_leasing'
),

-- 3. Chicago Office Complex - Unrestricted
(
  'fake-gsa-2025-003',
  'Multi-Floor Office Complex - Chicago Loop',
  'GS-05P-25-RLP-0003',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 5',
  NOW() - INTERVAL '10 days',
  'Combined Synopsis/Solicitation',
  'Presolicitation',
  'Yes',
  NULL,
  'Unrestricted',
  NOW() + INTERVAL '20 days',
  '531120',
  'Y1DA',
  'GSA requires 75,000 RSF of contiguous office space in Chicago Loop area. High-rise building with modern amenities, LEED certification preferred.',
  'OFFICE',
  '60604',
  'Chicago',
  'USA',
  'IL',
  'Chicago Loop District',
  'CHICAGO',
  'Chicago',
  'IL',
  'Illinois',
  '60604',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-003',
  'gsa_leasing'
),

-- 4. Denver Federal Office - WOSB
(
  'fake-gsa-2025-004',
  'Federal Office Space - Denver Tech Center',
  'GS-08P-25-RLP-0004',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 8',
  NOW() - INTERVAL '7 days',
  'Presolicitation',
  'Presolicitation',
  'Yes',
  'WOSB',
  'Women-Owned Small Business',
  NOW() + INTERVAL '12 days',
  '531120',
  'Y1DA',
  'Seeking 18,000 SF office space in Denver Tech Center area with secure parking, conference facilities, and IT infrastructure support.',
  'OFFICE',
  '80202',
  'Denver',
  'USA',
  'CO',
  'Denver Tech Center',
  'DENVER',
  'Denver',
  'CO',
  'Colorado',
  '80202',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-004',
  'gsa_leasing'
),

-- 5. Atlanta Office Building - Small Business
(
  'fake-gsa-2025-005',
  'Office Building Lease - Atlanta Midtown',
  'GS-04P-25-RLP-0005',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 4',
  NOW() - INTERVAL '2 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  'SBA',
  'Total Small Business Set-Aside',
  NOW() + INTERVAL '18 days',
  '531120',
  'Y1DA',
  'GSA needs 32,000 RSF in Atlanta Midtown area. Building must have high-speed internet, backup power, and meet federal security standards.',
  'OFFICE',
  '30303',
  'Atlanta',
  'USA',
  'GA',
  'Atlanta Midtown',
  'ATLANTA',
  'Atlanta',
  'GA',
  'Georgia',
  '30303',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-005',
  'gsa_leasing'
),

-- 6. Phoenix Office Space - 8(a)
(
  'fake-gsa-2025-006',
  'Office Space - Phoenix Central Business District',
  'GS-09P-25-RLP-0006',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 9',
  NOW() - INTERVAL '12 days',
  'Sources Sought',
  'Special Notice',
  'Yes',
  '8A',
  '8(a) Set-Aside',
  NOW() + INTERVAL '25 days',
  '531120',
  'Y1DA',
  'Sources sought for approximately 22,000 SF office space in Phoenix CBD. Must accommodate 100+ employees with modern workspace design.',
  'OFFICE',
  '85004',
  'Phoenix',
  'USA',
  'AZ',
  'Phoenix Central Business District',
  'PHOENIX',
  'Phoenix',
  'AZ',
  'Arizona',
  '85004',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-006',
  'gsa_leasing'
),

-- 7. San Francisco Federal Building - Unrestricted
(
  'fake-gsa-2025-007',
  'High-Rise Office Lease - San Francisco Financial District',
  'GS-09P-25-RLP-0007',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 9',
  NOW() - INTERVAL '6 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  NULL,
  'Unrestricted',
  NOW() + INTERVAL '14 days',
  '531120',
  'Y1DA',
  'Premium office space required: 55,000 RSF in Financial District. High-rise building with panoramic views, state-of-the-art facilities, LEED Gold minimum.',
  'OFFICE',
  '94102',
  'San Francisco',
  'USA',
  'CA',
  'Financial District',
  'SANFRANCISCO',
  'San Francisco',
  'CA',
  'California',
  '94102',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-007',
  'gsa_leasing'
),

-- 8. Dallas Office Complex - Small Business
(
  'fake-gsa-2025-008',
  'Office Complex Lease - Dallas Downtown',
  'GS-07P-25-RLP-0008',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 7',
  NOW() - INTERVAL '4 days',
  'Solicitation',
  'Solicitation',
  'Yes',
  'SBA',
  'Total Small Business Set-Aside',
  NOW() + INTERVAL '10 days',
  '531120',
  'Y1DA',
  'GSA requires 28,000 SF office space in Dallas downtown area. Must provide structured parking for 75 vehicles and meet all federal security requirements.',
  'OFFICE',
  '75201',
  'Dallas',
  'USA',
  'TX',
  'Dallas Downtown',
  'DALLAS',
  'Dallas',
  'TX',
  'Texas',
  '75201',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-008',
  'gsa_leasing'
),

-- 9. Miami Office Building - HUBZone
(
  'fake-gsa-2025-009',
  'Office Building - Miami Brickell Area',
  'GS-04P-25-RLP-0009',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 4',
  NOW() - INTERVAL '8 days',
  'Presolicitation',
  'Presolicitation',
  'Yes',
  'HZC',
  'HUBZone Set-Aside',
  NOW() + INTERVAL '22 days',
  '531120',
  'Y1DA',
  'Seeking 35,000 RSF in Brickell area. Building must have hurricane-rated windows, backup generators, and modern telecommunications infrastructure.',
  'OFFICE',
  '33130',
  'Miami',
  'USA',
  'FL',
  'Brickell',
  'MIAMI',
  'Miami',
  'FL',
  'Florida',
  '33130',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-009',
  'gsa_leasing'
),

-- 10. Portland Office Space - WOSB
(
  'fake-gsa-2025-010',
  'Office Space Lease - Portland Pearl District',
  'GS-10P-25-RLP-0010',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 10',
  NOW() - INTERVAL '1 day',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  'WOSB',
  'Women-Owned Small Business',
  NOW() + INTERVAL '6 days',
  '531120',
  'Y1DA',
  'URGENT: 15,000 SF office space needed in Pearl District. Sustainable building with bike storage, transit access, and flexible workspace layout.',
  'OFFICE',
  '97209',
  'Portland',
  'USA',
  'OR',
  'Pearl District',
  'PORTLAND',
  'Portland',
  'OR',
  'Oregon',
  '97209',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-010',
  'gsa_leasing'
),

-- 11. New York City Federal Building - Unrestricted
(
  'fake-gsa-2025-011',
  'Federal Office Building - Manhattan Midtown',
  'GS-02P-25-RLP-0011',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 2',
  NOW() - INTERVAL '15 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  NULL,
  'Unrestricted',
  NOW() + INTERVAL '30 days',
  '531120',
  'Y1DA',
  'Major lease opportunity: 120,000 RSF in Midtown Manhattan. Class A building required with advanced security systems, redundant utilities, and prestigious address.',
  'OFFICE',
  '10001',
  'New York',
  'USA',
  'NY',
  'Midtown Manhattan',
  'NEWYORK',
  'New York',
  'NY',
  'New York',
  '10001',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-011',
  'gsa_leasing'
),

-- 12. Philadelphia Office Complex - Small Business
(
  'fake-gsa-2025-012',
  'Office Complex - Philadelphia Center City',
  'GS-03P-25-RLP-0012',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 3',
  NOW() - INTERVAL '9 days',
  'Solicitation',
  'Solicitation',
  'Yes',
  'SBA',
  'Total Small Business Set-Aside',
  NOW() + INTERVAL '16 days',
  '531120',
  'Y1DA',
  'GSA requires 42,000 SF in Center City Philadelphia. Historic building renovation acceptable if meeting all modern federal building standards.',
  'OFFICE',
  '19103',
  'Philadelphia',
  'USA',
  'PA',
  'Center City',
  'PHILADELPHIA',
  'Philadelphia',
  'PA',
  'Pennsylvania',
  '19103',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-012',
  'gsa_leasing'
),

-- 13. Las Vegas Office Building - 8(a)
(
  'fake-gsa-2025-013',
  'Office Building Lease - Las Vegas Downtown',
  'GS-09P-25-RLP-0013',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 9',
  NOW() - INTERVAL '11 days',
  'Presolicitation',
  'Presolicitation',
  'Yes',
  '8A',
  '8(a) Set-Aside',
  NOW() + INTERVAL '19 days',
  '531120',
  'Y1DA',
  'Seeking 26,000 RSF office space in Las Vegas downtown area. Energy-efficient building with covered parking and enhanced security features.',
  'OFFICE',
  '89101',
  'Las Vegas',
  'USA',
  'NV',
  'Las Vegas Downtown',
  'LASVEGAS',
  'Las Vegas',
  'NV',
  'Nevada',
  '89101',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-013',
  'gsa_leasing'
),

-- 14. Minneapolis Office Space - HUBZone
(
  'fake-gsa-2025-014',
  'Office Space - Minneapolis Downtown Core',
  'GS-05P-25-RLP-0014',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 5',
  NOW() - INTERVAL '5 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  'HZC',
  'HUBZone Set-Aside',
  NOW() + INTERVAL '13 days',
  '531120',
  'Y1DA',
  'GSA needs 30,000 SF in downtown Minneapolis. Skyway connection required, winter-ready facilities, and adequate heating systems.',
  'OFFICE',
  '55401',
  'Minneapolis',
  'USA',
  'MN',
  'Minneapolis Downtown',
  'MINNEAPOLIS',
  'Minneapolis',
  'MN',
  'Minnesota',
  '55401',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-014',
  'gsa_leasing'
),

-- 15. Houston Office Complex - Unrestricted
(
  'fake-gsa-2025-015',
  'Office Complex Lease - Houston Energy Corridor',
  'GS-07P-25-RLP-0015',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 7',
  NOW() - INTERVAL '13 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  NULL,
  'Unrestricted',
  NOW() + INTERVAL '27 days',
  '531120',
  'Y1DA',
  'Large office requirement: 65,000 RSF in Energy Corridor. Campus-style setting acceptable, must include cafeteria space and fitness center.',
  'OFFICE',
  '77002',
  'Houston',
  'USA',
  'TX',
  'Energy Corridor',
  'HOUSTON',
  'Houston',
  'TX',
  'Texas',
  '77002',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-015',
  'gsa_leasing'
),

-- 16. Sacramento State Office - WOSB
(
  'fake-gsa-2025-016',
  'State Office Building - Sacramento Downtown',
  'GS-09P-25-RLP-0016',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 9',
  NOW() - INTERVAL '3 days',
  'Solicitation',
  'Solicitation',
  'Yes',
  'WOSB',
  'Women-Owned Small Business',
  NOW() + INTERVAL '11 days',
  '531120',
  'Y1DA',
  'Required: 20,000 SF near state capitol. Public transportation access essential, visitor-friendly entrance, and ADA compliant throughout.',
  'OFFICE',
  '95814',
  'Sacramento',
  'USA',
  'CA',
  'Sacramento Downtown',
  'SACRAMENTO',
  'Sacramento',
  'CA',
  'California',
  '95814',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-016',
  'gsa_leasing'
),

-- 17. St. Louis Federal Building - Small Business
(
  'fake-gsa-2025-017',
  'Federal Office Building - St. Louis Downtown',
  'GS-07P-25-RLP-0017',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 7',
  NOW() - INTERVAL '7 days',
  'Presolicitation',
  'Presolicitation',
  'Yes',
  'SBA',
  'Total Small Business Set-Aside',
  NOW() + INTERVAL '21 days',
  '531120',
  'Y1DA',
  'GSA seeks 24,000 SF office space in downtown St. Louis. Riverfront area preferred, parking for 60 vehicles, modern HVAC systems.',
  'OFFICE',
  '63101',
  'St. Louis',
  'USA',
  'MO',
  'St. Louis Downtown',
  'STLOUIS',
  'St. Louis',
  'MO',
  'Missouri',
  '63101',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-017',
  'gsa_leasing'
),

-- 18. Baltimore Office Space - 8(a)
(
  'fake-gsa-2025-018',
  'Office Space Lease - Baltimore Inner Harbor',
  'GS-03P-25-RLP-0018',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 3',
  NOW() - INTERVAL '2 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  '8A',
  '8(a) Set-Aside',
  NOW() + INTERVAL '9 days',
  '531120',
  'Y1DA',
  'URGENT: 19,000 SF needed near Inner Harbor. Water-resistant building features, flood zone considerations, excellent public transit access.',
  'OFFICE',
  '21202',
  'Baltimore',
  'USA',
  'MD',
  'Inner Harbor',
  'BALTIMORE',
  'Baltimore',
  'MD',
  'Maryland',
  '21202',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-018',
  'gsa_leasing'
),

-- 19. Charlotte Office Building - HUBZone
(
  'fake-gsa-2025-019',
  'Office Building - Charlotte Uptown District',
  'GS-04P-25-RLP-0019',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 4',
  NOW() - INTERVAL '14 days',
  'Sources Sought',
  'Special Notice',
  'Yes',
  'HZC',
  'HUBZone Set-Aside',
  NOW() + INTERVAL '28 days',
  '531120',
  'Y1DA',
  'Sources sought for 38,000 RSF in Charlotte Uptown. Banking district location preferred, high-security building, executive-level finishes.',
  'OFFICE',
  '28202',
  'Charlotte',
  'USA',
  'NC',
  'Uptown Charlotte',
  'CHARLOTTE',
  'Charlotte',
  'NC',
  'North Carolina',
  '28202',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-019',
  'gsa_leasing'
),

-- 20. San Diego Federal Complex - Unrestricted
(
  'fake-gsa-2025-020',
  'Federal Office Complex - San Diego Mission Valley',
  'GS-09P-25-RLP-0020',
  'General Services Administration',
  'Public Buildings Service',
  'GSA PBS Region 9',
  NOW() - INTERVAL '6 days',
  'Combined Synopsis/Solicitation',
  'Solicitation',
  'Yes',
  NULL,
  'Unrestricted',
  NOW() + INTERVAL '17 days',
  '531120',
  'Y1DA',
  'Federal complex requirement: 48,000 RSF in Mission Valley area. Seismic-rated building essential, secure parking structure, cafeteria facilities, conferencing capabilities.',
  'OFFICE',
  '92101',
  'San Diego',
  'USA',
  'CA',
  'Mission Valley',
  'SANDIEGO',
  'San Diego',
  'CA',
  'California',
  '92101',
  'USA',
  'United States',
  'https://sam.gov/opp/fake-gsa-2025-020',
  'gsa_leasing'
);
